- .github/workflows/cosmos-sdk-proto.yml
- .github/workflows/cosmos-tx.yml
- .github/workflows/proto-build.yml
- .github/workflows/workspace.yml
- Cargo.lock
- Cargo.toml
- cosmos-sdk-proto/README.md
- cosmos-tx/Cargo.toml
- cosmos-tx/README.md
- cosmos-tx/src/builder.rs
- cosmos-tx/src/decimal.rs
- cosmos-tx/src/error.rs
- cosmos-tx/src/lib.rs
- cosmos-tx/src/msg.rs
Adds a `cosmos-tx` crate which provides a transaction builder and signer for Cosmos-based blockchains.
This commit ports over the WIP protobuf support from:
https://github.com/iqlusioninc/crates/tree/develop/stdtx
> cosmos-tx crate

- proto-build/Cargo.toml
Prevents accidental publication to crates.io
> proto-build: set `publish = false` in Cargo.toml

- cosmos-sdk-proto/README.md
- cosmos-tx/README.md
The "Rust" workflow was split into separate workflows-per-crate in #6.
However, the badges in the README.md files were not updated. This commit updates them to point to the new workflows.
> Fix GitHub Actions badges

- Cargo.lock
- cosmos-sdk-proto/Cargo.toml
- cosmos-tx/Cargo.toml
Updates prerelease versions of these crates to the final releases.
https://github.com/informalsystems/tendermint-rs/blob/master/CHANGELOG.md#v0170
> Bump tendermint-rs + tendermint-proto to v0.17

- .gitmodules
- proto-build/src/main.rs
After looking at the `cosmos-sdk/` submodule in my editor, I realized it's not exactly clear that this directory is the Go library rather than a `cosmos-sdk` crate (which would aspirationally be a cool thing to have)
This renames it so it's clear the directory contains the upstream Go SDK.
> Rename `cosmos-sdk` to `cosmos-sdk-go`

- README.md
This is our first governance vote for expanding the maintaining team. I would like to invite Confio to the governance process of this repo.
This includes having one member on the Crates.io maintainer list of cosmos-sdk-proto (and future crates published from this repo) as well
as being added to this list of teams capable of seconding a change before merge (as outlined in the readme) and given push access to make
branches.
> Add Confio to the cosmos-rust governing team

- proto-build/src/main.rs
Prints a string-formatted error message to STDERR when protoc fails, instead of printing raw `Debug` output indirectly via `unwrap()` triggering Rust's built-in panic handler.
```
[info] Compiling .proto files to Rust into '/tmp/tmp-protobuf/'...
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: "protoc failed: /Users/bascule/src/cosmos-rust/proto-build/../proto: warning: directory does not exist.\nibc/core/client/v1/tx.proto:8:1: warning: Import ibc/core/client/v1/client.proto is unused.\ncosmos/tx/v1beta1/service.proto:7:1: warning: Import gogoproto/gogo.proto is unused.\ncosmos/base/tendermint/v1beta1/query.proto:87:3: \"tendermint.types.BlockID\" is resolved to \"cosmos.base.tendermint.types.BlockID\", which is not defined. The …
```
> proto-build: improve protoc errors

- Cargo.lock
- cosmos-sdk-proto/CHANGELOG.md
- cosmos-sdk-proto/Cargo.toml
- cosmos-sdk-proto/README.md
- cosmos-sdk-proto/src/lib.rs
- cosmos-tx/CHANGELOG.md
- cosmos-tx/Cargo.toml
- cosmos-tx/README.md
- cosmos-tx/src/lib.rs
- `grpc` crate feature ([#8])
- Bump `cosmos-sdk` rev to [v0.40.0-rc6](https://github.com/cosmos/cosmos-sdk/pull/8249) ([#32])
- Bump `tendermint` + `tendermint-proto` crate dependencies to v0.17 ([#18])
- Format `prost`/`tonic` output with `rustfmt` ([#17])
[#8]: https://github.com/cosmos/cosmos-rust/pull/8
[#17]: https://github.com/cosmos/cosmos-rust/pull/17
[#18]: https://github.com/cosmos/cosmos-rust/pull/18
[#32]: https://github.com/cosmos/cosmos-rust/pull/32
- Initial transaction builder and signer ([#6]) 
[#6]: https://github.com/cosmos/cosmos-rust/pull/6
> Release cosmos-sdk-proto v0.2.0 + cosmos-tx v0.2.0-pre

- Cargo.lock
- cosmos-sdk-proto/Cargo.toml
- cosmos-sdk-proto/src/prost/cosmos.auth.v1beta1.rs
- cosmos-sdk-proto/src/prost/cosmos.bank.v1beta1.rs
- cosmos-sdk-proto/src/prost/cosmos.base.abci.v1beta1.rs
- cosmos-sdk-proto/src/prost/cosmos.base.kv.v1beta1.rs
- cosmos-sdk-proto/src/prost/cosmos.base.query.v1beta1.rs
- cosmos-sdk-proto/src/prost/cosmos.base.reflection.v1beta1.rs
- cosmos-sdk-proto/src/prost/cosmos.base.snapshots.v1beta1.rs
- cosmos-sdk-proto/src/prost/cosmos.base.store.v1beta1.rs
- cosmos-sdk-proto/src/prost/cosmos.base.tendermint.v1beta1.rs
- cosmos-sdk-proto/src/prost/cosmos.base.v1beta1.rs
- cosmos-sdk-proto/src/prost/cosmos.crypto.multisig.v1beta1.rs
- cosmos-sdk-proto/src/prost/cosmos.staking.v1beta1.rs
- cosmos-sdk-proto/src/prost/cosmos.tx.signing.v1beta1.rs
- cosmos-sdk-proto/src/prost/cosmos.tx.v1beta1.rs
- cosmos-sdk-proto/src/prost/ibc.applications.transfer.v1.rs
- cosmos-sdk-proto/src/prost/ibc.core.channel.v1.rs
- cosmos-sdk-proto/src/prost/ibc.core.client.v1.rs
- cosmos-sdk-proto/src/prost/ibc.core.commitment.v1.rs
- cosmos-sdk-proto/src/prost/ibc.core.connection.v1.rs
- cosmos-sdk-proto/src/prost/ibc.core.types.v1.rs
- cosmos-sdk-proto/src/prost/ibc.lightclients.localhost.v1.rs
- cosmos-sdk-proto/src/prost/ibc.lightclients.solomachine.v1.rs
- cosmos-sdk-proto/src/prost/ibc.lightclients.tendermint.v1.rs
- cosmos-sdk-proto/src/prost/ics23.rs
- cosmos-tx/Cargo.toml
- proto-build/Cargo.toml
Also bumps the following dependencies:
- `prost`, `prost-types`, `prost-build` => v0.7
- `tonic`, `tonic-build` => v0.4
> Bump `tendermint` crate dependency to v0.18

- Cargo.lock
- cosmos-tx/Cargo.toml
> cosmos-tx: bump `tendermint` crate to v0.18

- Cargo.lock
- cosmos-sdk-proto/CHANGELOG.md
- cosmos-sdk-proto/Cargo.toml
- cosmos-sdk-proto/src/lib.rs
- cosmos-tx/Cargo.toml
- Bump `cosmos-sdk` rev to v0.40.0 ([#37])
- Bump `tendermint` crate dependency to v0.18 ([#45])
- Bump `prost`, `prost-types`, `prost-build` to v0.7 ([#45])
- Bump `tonic`, `tonic-build` to v0.4 ([#45])
[#37]: https://github.com/cosmos/cosmos-rust/pull/37
[#45]: https://github.com/cosmos/cosmos-rust/pull/45
[#45]: https://github.com/cosmos/cosmos-rust/pull/45
[#45]: https://github.com/cosmos/cosmos-rust/pull/45
> cosmos-sdk-proto v0.3.0

- README.md
- cosmos-sdk-proto/README.md
- cosmos-tx/README.md
Shows the crates available in the repo at-a-glance.
[Rendered](https://github.com/cosmos/cosmos-rust/blob/fa6dfcace0c602872102712c35c9be5320c91d51/README.md#crates)
> README.md: add table of crate descriptions

- .github/workflows/rebuild-protos.yml
- proto-build/src/main.rs
Adds a `rebuild-protos` GitHub Actions workflow to automatically run `proto-build` every time a commit is merged/pushed to the `main` branch.
After running `rebuild-protos`, if there are any changed files, it uses the [peter-evans/create-pull-request](https://github.com/marketplace/actions/create-pull-request) GitHub Action to open a PR with those changes automatically, thus ensuring `cosmos-sdk-proto` is reproducible and automating the work of regenerating the protos so it can be kept out-of-band with other PRs.
If no files are changed, the workflow otherwise completes successfully.
Note that this is using a 3rd party GitHub Action, and exposing the repo's `GITHUB_TOKEN` to it. However, the action is pinned to the latest release (`peter-evans/create-pull-request@v3.5.2`) effectively …
> Run `proto-build` automatically with GitHub Actions

- .github/workflows/rebuild-protos.yml
Fixes a bit of copypasta from the action I based this on.
A local test of running `cargo run --quiet -- --github` in the `proto-build` directory showed it was working:
```
$ echo $message
Rebuild protos with proto-build (cosmos-sdk rev: v0.42.3)
```
...but the step name being passed to `create-pull-request` was incorrect.
> rebuild-protos: fix name of build step

- cosmos-sdk-proto/src/lib.rs
In what seems to be a simple oversight bank proto and services have been
compiled but not imported and exposed to users of the Crate. This patch
resolves that issue just by adding the import. No other changes are
required.
> Import bank proto and service definitions

- cosmos-tx/src/lib.rs
The current implementation consists of a number of single-type modules which are re-exported at the toplevel.
This commit removes the `pub` from modules to eliminate the module hierarchy, which makes the relevant types easier to find at-a-glance when reading the corresponding `rustdoc` documentation.
> cosmos-tx: flatten API

- cosmos-sdk-proto/Cargo.toml
- cosmos-sdk-proto/src/lib.rs
- cosmos-sdk-proto/src/prost/cosmos.bank.v1beta1.rs
- cosmos-sdk-proto/src/prost/cosmos.capability.v1beta1.rs
- cosmos-sdk-proto/src/prost/cosmos.crisis.v1beta1.rs
- cosmos-sdk-proto/src/prost/cosmos.crypto.ed25519.rs
- cosmos-sdk-proto/src/prost/cosmos.crypto.multisig.rs
- cosmos-sdk-proto/src/prost/cosmos.crypto.secp256k1.rs
- cosmos-sdk-proto/src/prost/cosmos.distribution.v1beta1.rs
- cosmos-sdk-proto/src/prost/cosmos.evidence.v1beta1.rs
- cosmos-sdk-proto/src/prost/cosmos.genutil.v1beta1.rs
- cosmos-sdk-proto/src/prost/cosmos.gov.v1beta1.rs
- cosmos-sdk-proto/src/prost/cosmos.mint.v1beta1.rs
- cosmos-sdk-proto/src/prost/cosmos.params.v1beta1.rs
- cosmos-sdk-proto/src/prost/cosmos.slashing.v1beta1.rs
- cosmos-sdk-proto/src/prost/cosmos.staking.v1beta1.rs
- cosmos-sdk-proto/src/prost/cosmos.upgrade.v1beta1.rs
- cosmos-sdk-proto/src/prost/cosmos.vesting.v1beta1.rs
- cosmos-sdk-proto/src/prost/ibc.applications.transfer.v1.rs
- cosmos-sdk-proto/src/prost/ibc.core.client.v1.rs
- cosmos-sdk-proto/src/prost/ibc.core.connection.v1.rs
- cosmos-tx/Cargo.toml
- proto-build/src/main.rs
This pull request expands cosmos-sdk-proto to include all files from the upstream cosmos-sdk proto folder. It also adds services relating to transactions to the new modules and existing modules where they where previously missing. This should allow consumers of the library to import use cosmos-sdk-proto for producing many different transaction types without having to trace them down themselves.
During this change I've alphabetized all the proto imports and lists wherever they exist. Purely for ease of keeping track of what modules are or are not imported.
This patch rebuilds the proto files purely for the sake of making sure the tests pass, since the proto will be auto-regenerated once it's merged. Which is a bit of a waste of a commit  but not terrible in exchange for the other benefits. …
> Expand cosmos-sdk-proto to include all upstream proto files

- cosmos-tx/Cargo.toml
- cosmos-tx/src/builder.rs
- cosmos-tx/src/lib.rs
- cosmos-tx/src/signing_key.rs
Adds a `SigningKey` type which wraps a `Box` containing a concrete
signing key implementation, allowing it to be used with either a
soft-signer (backed by the `k256` crate) or HSM signers that impl
the correct combination of traits (e.g. `yubihsm`)
This type additionally provides methods for obtaining a
`tendermint::PublicKey` for the signer, which is needed for e.g.
computing the relevant account address for the signer.
As it were, obtaining the account address is needed to implement
integration testing, as it's the first parameter we need to pass into a
single-node gaia Docker container.
> cosmos-tx: add SigningKey type

- .github/workflows/rebuild-protos.yml
Protos should only be rebuilt if files in `proto-build/` change, e.g. `COSMOS_REV` is bumped or other changes are made to the proto generator.
This should cut down on spurious rebuilds, since unfortunately the generated code does not appear to be fully deterministic.
> CI: constrain when rebuild-protos runs

- cosmos-sdk-proto/src/lib.rs
I missed these in my previous comments, just a few minor key type
structs.
> Add imports for secp256k1 and ed25519 proto defs

- cosmos-sdk-proto/CHANGELOG.md
- cosmos-sdk-proto/Cargo.toml
- cosmos-sdk-proto/src/lib.rs
- cosmos-tx/Cargo.toml
This release bump just gets the crypto structs into a crates.io release.
Very minor change overall.
> Bump cosmos-sdk-proto release

- cosmos-sdk-rs/Cargo.toml
- cosmos-sdk-rs/src/dev.rs
- cosmos-sdk-rs/src/error.rs
- cosmos-sdk-rs/src/lib.rs
- cosmos-sdk-rs/src/tx.rs
- cosmos-sdk-rs/tests/integration.rs
Adds basic documentation for building, signing, and parsing transactions.
Update: went ahead and extracted some of the functions used in the integration test into a `dev` module with the goal of reusing them in downstream consumers of this crate.
TMKMS and Delphi are good candidates for the `dev` module. I imagine there are other use cases that might make sense (e.g. Gravity Orchestrator).
It might make sense to upstream some of that to tendermint-rs? /cc @thanethomson
> cosmos-sdk-rs: add initial usage docs and `dev` module

- cosmos-sdk-rs/CHANGELOG.md
- cosmos-sdk-rs/Cargo.toml
- cosmos-sdk-rs/src/lib.rs
Initial release under the `cosmos-sdk` crate name.
> cosmos-sdk-rs v0.1.1

- README.md
- cosmos-sdk-proto/README.md
- cosmos-sdk-rs/README.md
Unfortunately it was originally published with an underscore instead of a hyphen, and it's not presently possible to change that.
Hyphens work in place of an underscore in most places, however one place they don't, apparently is the image for docs.rs badges (it does work for links, however).
This commit fixes the badges, uses `cosmos_sdk` in links for consistency with the current name, and linkifies badges in the table in the toplevel README.md.
> Fix links to `cosmos_sdk`

- cosmos-sdk-rs/src/lib.rs
- cosmos-sdk-rs/src/staking.rs
- cosmos-sdk-rs/src/tx/msg.rs
Add staking functions to the cosmos-sdk by extending to existing protobuf methods:
- MsgDelegate
- MsgUnDelegate
- MsgBeginRedelegate
> Add staking functions to cosmos-sdk

- cosmos-sdk-rs/CHANGELOG.md
- cosmos-sdk-rs/Cargo.toml
- cosmos-sdk-rs/src/lib.rs
- Staking functions ([#82])
- More detail to `AccountId` parsing errors ([#85])
- Basic BIP32 support ([#91])
- Bump `tendermint*` crate dependencies to v0.20; MSRV 1.51+ ([#89])
[#82]: https://github.com/cosmos/cosmos-rust/pull/82
[#85]: https://github.com/cosmos/cosmos-rust/pull/85
[#89]: https://github.com/cosmos/cosmos-rust/pull/89
[#91]: https://github.com/cosmos/cosmos-rust/pull/91
> cosmos-sdk-rs v0.2.0

- cosmos-sdk-proto/CHANGELOG.md
- cosmos-sdk-proto/Cargo.toml
- cosmos-sdk-proto/src/lib.rs
- cosmos-sdk-rs/Cargo.toml
- Basic `cosmwasm` support ([#96])
- Bump `tendermint-proto` requirement from 0.20 to 0.21 ([#106])
[#96]: https://github.com/cosmos/cosmos-rust/pull/96
[#106]: https://github.com/cosmos/cosmos-rust/pull/106
> cosmos-sdk-proto v0.6.0

- cosmos-sdk-rs/src/distribution.rs
- cosmos-sdk-rs/src/lib.rs
- cosmos-sdk-rs/src/tx/msg.rs
Add distribution functions to the cosmos-sdk by extending to existing protobuf methods:
- MsgSetWithdrawAddress
- MsgWithdrawDelegatorReward
- MsgWithdrawValidatorCommission
- MsgFundCommunityPool
The withdraw methods are required for a full staking flow, because rewards/commissions must be explicitly claimed after thet are earned,
> add distribution functions to cosmos-sdk

- cosmos-sdk-rs/src/cosmwasm.rs
I've run into my own omission from the previous pull request - as the comment suggests, the admin field should be optional.
> Made admin field optional in MsgInstantiateContract

- cosmos-sdk-proto/CHANGELOG.md
- cosmos-sdk-proto/Cargo.toml
- cosmos-sdk-proto/src/lib.rs
- Rebuild protos with cosmos-sdk v0.43.0  ([#117])
[#117]: https://github.com/cosmos/cosmos-rust/pull/117
> cosmos-sdk-proto v0.6.1

- cosmos-sdk-rs/CHANGELOG.md
- cosmos-sdk-rs/Cargo.toml
- cosmos-sdk-rs/src/cosmwasm.rs
- cosmos-sdk-rs/src/lib.rs
- Basic `cosmwasm` support ([#96])
- Distribution module ([#114])
- Update protobufs for cosmos-sdk 0.43.0-rc2 ([#108])
- Bump `tendermint-rs` to v0.21 ([#110])
- Bump `cosmos-sdk-proto` to v0.6 ([#111])
- Made admin field optional in `MsgInstantiateContract` ([#115])
[#96]: https://github.com/cosmos/cosmos-rust/pull/96
[#108]: https://github.com/cosmos/cosmos-rust/pull/108
[#110]: https://github.com/cosmos/cosmos-rust/pull/110
[#111]: https://github.com/cosmos/cosmos-rust/pull/111
[#114]: https://github.com/cosmos/cosmos-rust/pull/114
[#115]: https://github.com/cosmos/cosmos-rust/pull/115
> cosmos-sdk-rs v0.3.0

- cosmos-sdk-proto/src/prost/cosmos.vesting.v1beta1.rs
- proto-build/src/main.rs
**Changed**
- Rebuild protos with cosmos-sdk v0.43.0 (added "proto/cosmos/vesting/v1beta1/vesting.proto" to proto paths)
> New protos for vesting accounts

- cosmos-sdk-proto/CHANGELOG.md
- cosmos-sdk-proto/Cargo.toml
- cosmos-sdk-proto/src/lib.rs
- Protos for vesting accounts ([#119])
[#119]: https://github.com/cosmos/cosmos-rust/pull/119
> cosmos-sdk-proto v0.6.2

- cosmos-sdk-proto/CHANGELOG.md
- cosmos-sdk-proto/Cargo.toml
- cosmos-sdk-proto/src/lib.rs
- Bump MSRV to 1.54 ([#122])
[#122]: https://github.com/cosmos/cosmos-rust/pull/122
> cosmos-sdk-proto v0.6.3

- cosmos-sdk-rs/src/staking.rs
As noted on #82, the `amount` field of `MsgDelegate` is annotated as non-nullable in the upstream cosmos-sdk:
https://github.com/cosmos/cosmos-sdk/blob/9fd866e3820b3510010ae172b682d71594cd8c14/proto/cosmos/staking/v1beta1/tx.proto#L89
```proto
message MsgDelegate {
option (gogoproto.equal)           = false;
option (gogoproto.goproto_getters) = false;
string                   delegator_address = 1 [(gogoproto.moretags) = "yaml:\"delegator_address\""];
string                   validator_address = 2 [(gogoproto.moretags) = "yaml:\"validator_address\""];
cosmos.base.v1beta1.Coin amount            = 3 [(gogoproto.nullable) = false];
}
```
This commit changes the `amount` field of the domain type from `Option<Coin>` to `Coin` to reflect that.
> cosmos-sdk-rs: make staking amount non-nullable

- cosmos-sdk-proto/CHANGELOG.md
- cosmos-sdk-proto/Cargo.toml
- cosmos-sdk-proto/src/lib.rs
- cosmrs/Cargo.toml
- Update `tendermint` crate to v0.22 ([#128])
[#128]: https://github.com/cosmos/cosmos-rust/pull/128
> cosmos-sdk-proto v0.7.0

- cosmos-sdk-proto/CHANGELOG.md
- cosmrs/CHANGELOG.md
- cosmrs/Cargo.toml
- cosmrs/src/lib.rs
- Make `Tx::find_by_hash` use the `/tx` endpoint ([#116])
- Update `tendermint` crate to v0.22 ([#128])
- Update `cosmos-sdk-proto` to v0.7 ([#129])
[#116]: https://github.com/cosmos/cosmos-rust/pull/116
[#128]: https://github.com/cosmos/cosmos-rust/pull/128
[#129]: https://github.com/cosmos/cosmos-rust/pull/129
> cosmrs v0.2.0

- cosmos-sdk-proto/src/lib.rs
- cosmrs/Cargo.toml
- cosmrs/src/base.rs
- cosmrs/src/crypto/public_key.rs
Adds support for the "Cosmos JSON" `PublicKey` serialization, e.g.:
{"@type":"/cosmos.crypto.ed25519.PubKey","key":"sEEsVGkXvyewKLWMJbHVDRkBoerW0IIwmj1rHkabtHU="}
Encoding follows Protobub JSON conventions, with binary data encoded as standard (i.e. non-URL safe) Base64. However, note that it's structurally still a bit different from the Protobuf JSON encoding for public keys, and thus entails a custom solution.
Also note that there is unfortunately not yet a general solution for Protobuf JSON encoding for `prost::Message`:
https://github.com/tokio-rs/prost/issues/75
> cosmrs: `PublicKey` JSON serialization support

- cosmrs/CHANGELOG.md
- cosmrs/Cargo.toml
- cosmrs/src/lib.rs
- `PublicKey` JSON serialization support ([#133])
[#133]: https://github.com/cosmos/cosmos-rust/pull/133
> cosmrs v0.2.1

- cosmos-sdk-proto/Cargo.toml
- cosmrs/Cargo.toml
As per the tendermint-rs versioning (https://github.com/informalsystems/tendermint-rs#versioning), we're now focusing on the v0.24.0 release for compatibility with Tendermint v0.35.x, so any further breaking changes to the v0.23.x series of tendermint-rs need to be released as patch versions.
This pins your tendermint-rs deps to v0.23.1 for now until we can ensure that v0.23.2 (https://github.com/informalsystems/tendermint-rs/pull/1043) does not break anything.
> Pin tendermint-rs deps to v0.23.1 for now

- cosmos-sdk-proto/Cargo.toml
- cosmrs/Cargo.toml
Also updates:
- `bip32` => 0.3
- `ecdsa` => v0.13
These dependencies all need to be updated in lockstep due to dependencies on `k256`.
> Bump `tendermint` to v0.23.3; `k256` to v0.10

- cosmrs/src/tx.rs
Adds a `SignatureBytes` type alias for `Vec<u8>`, and changes `Tx::signatures` to `Vec<SignatureBytes>`.
Previously signatures were being eagerly parsed as `secp256k1::Signature`, but this prevents parsing other kinds of signatures, such as Amino.
Closes #151
> cosmrs: use `Vec<u8>` as the `Tx::signatures` type

- cosmrs/CHANGELOG.md
- cosmrs/Cargo.toml
- cosmrs/src/lib.rs
- Bump `tendermint` to v0.23.3; `k256` to v0.10 ([#163])
- Use `Vec<u8>` as the `Tx::signatures` type ([#164])
[#163]: https://github.com/cosmos/cosmos-rust/pull/163
[#164]: https://github.com/cosmos/cosmos-rust/pull/164
> cosmrs v0.4.0

- cosmos-sdk-proto/CHANGELOG.md
- cosmos-sdk-proto/Cargo.toml
- cosmos-sdk-proto/src/lib.rs
- cosmrs/Cargo.toml
- Update wasmd compatibility to 0.21 ([#158])
- Bump `tendermint-proto` to v0.23.3 ([#163])
[#158]: https://github.com/cosmos/cosmos-rust/pull/158
[#163]: https://github.com/cosmos/cosmos-rust/pull/163
> cosmos-sdk-proto v0.9.0

- cosmrs/CHANGELOG.md
- cosmrs/Cargo.toml
- cosmrs/src/lib.rs
- Bump `cosmos-sdk-proto` to v0.4.1 ([#165])
[#165]: https://github.com/cosmos/cosmos-rust/pull/165
> cosmrs v0.4.1

- cosmrs/src/staking.rs
Close https://github.com/cosmos/cosmos-rust/issues/174
According to [MsgUndelegate](https://github.com/cosmos/cosmos-sdk/blob/9fd866e3820b3510010ae172b682d71594cd8c14/proto/cosmos/staking/v1beta1/tx.proto#L120) and [MsgBeginRedelegate](https://github.com/cosmos/cosmos-sdk/blob/9fd866e3820b3510010ae172b682d71594cd8c14/proto/cosmos/staking/v1beta1/tx.proto#L104) in schema, and PR https://github.com/cosmos/cosmos-rust/pull/124, I remove `Option` from field amount for both messages.
> Remove Option from field amount of MsgUndelegate and MsgBeginRedelegate

- cosmos-sdk-proto/CHANGELOG.md
- cosmos-sdk-proto/Cargo.toml
- cosmos-sdk-proto/src/lib.rs
- cosmrs/Cargo.toml
- `authz` and `feegrant` protos ([#177])
- Update SDK version => v0.45.1, IBC => v2.0.3, wasmd => v0.23.0 ([#177])
- Bump `tendermint-proto` to v0.23.5 ([#178])
[#177]: https://github.com/cosmos/cosmos-rust/pull/177
[#178]: https://github.com/cosmos/cosmos-rust/pull/178
> cosmos-sdk-proto v0.10.0

- cosmrs/CHANGELOG.md
- cosmrs/Cargo.toml
- cosmrs/src/lib.rs
- Bump `tendermint-proto` to v0.23.5 ([#178])
- Bump `cosmos-sdk-proto` to v0.10.0 ([#180])
- `Option` from field amount of `MsgUndelegate` and `MsgBeginRedelegate` ([#175])
[#175]: https://github.com/cosmos/cosmos-rust/pull/175
[#178]: https://github.com/cosmos/cosmos-rust/pull/178
[#180]: https://github.com/cosmos/cosmos-rust/pull/180
> cosmrs v0.5.0

- cosmrs/src/base.rs
So that it would be compatible with the new 32-byte long addresses
> Changed AccountId validation to check for maximum number of bytes

- cosmrs/Cargo.toml
- cosmrs/src/base.rs
- cosmrs/src/crypto/public_key.rs
This commit changes the constructor and `to_bytes` methods to fully support variable-width account IDs, as added in cosmos/cosmos-sdk#8363.
This is a breaking change.
> cosmrs: fully variable-width `AccountId`

- cosmos-sdk-proto/CHANGELOG.md
- cosmos-sdk-proto/Cargo.toml
- cosmrs/Cargo.toml
- Missing modules from `ibc-go` ([#187])
- Upgrade SDK version => v0.45.2, IBC => v3.0.0 ([#199])
- Bump tendermint-rs crates to v0.23.6 ([#205])
- Export `authz` module ([#186])
- Export `feegrant` module ([#198])
[#186]: https://github.com/cosmos/cosmos-rust/pull/186
[#187]: https://github.com/cosmos/cosmos-rust/pull/187
[#198]: https://github.com/cosmos/cosmos-rust/pull/198
[#199]: https://github.com/cosmos/cosmos-rust/pull/199
[#205]: https://github.com/cosmos/cosmos-rust/pull/205
> cosmos-sdk-proto v0.11.0

- cosmrs/CHANGELOG.md
- cosmrs/Cargo.toml
- cosmrs/src/lib.rs
- `TryFrom` impls for `tendermint` public key types ([#203])
- Support variable-width `AccountId` using new Cosmos SDK rules ([#197], [#204])
- Bump tendermint-rs crates to v0.23.6 ([#205])
- Bump `cosmos-sdk-proto` to v0.11.0 ([#206])
[#197]: https://github.com/cosmos/cosmos-rust/pull/197
[#203]: https://github.com/cosmos/cosmos-rust/pull/203
[#204]: https://github.com/cosmos/cosmos-rust/pull/204
[#205]: https://github.com/cosmos/cosmos-rust/pull/205
[#206]: https://github.com/cosmos/cosmos-rust/pull/206
> cosmrs v0.6.0

- cosmrs/src/base.rs
- cosmrs/src/tx.rs
Includes the Bech32 string that failed to decode in the error message.
Also adds a basic test for `AccountId` parsing.
> cosmrs: better error message on `AccountId` Bech32 decode failure

- cosmrs/src/cosmwasm.rs
- cosmrs/src/prost_ext.rs
- cosmrs/src/tx/fee.rs
Adds an extension trait to `String`/`str` for handling a common Cosmos SDK pattern: treating a string field as optional if it's empty, or otherwise parsing it to a particular type.
This pattern existed in the `cosmwasm` and `fee` modules, with similar boilerplate to handle it. As it were, the code in the `Fee` module was buggy.
This redundant code can be replaced with this simple extension trait.
> cosmrs: add sealed `ParseOptional` trait; fix `Fee` parsing

- cosmrs/CHANGELOG.md
- cosmrs/Cargo.toml
- Better error message on `AccountId` Bech32 decode failure ([#209])
- `tx::Fee` parsing with empty address fields ([#210])
[#209]: https://github.com/cosmos/cosmos-rust/pull/209
[#210]: https://github.com/cosmos/cosmos-rust/pull/210
> cosmrs v0.6.1

- cosmos-sdk-proto/CHANGELOG.md
- cosmos-sdk-proto/Cargo.toml
- cosmos-sdk-proto/README.md
- cosmrs/Cargo.toml
- Bump tendermint-rs crates to v0.23.7 ([#215])
- Bump `prost` to v0.10 ([#215])
- Bump `tonic` to v0.7 ([#215])
- Bump `COSMOS_SDK_REV` from v0.45.2 => v0.45.4 ([#215])
[#215]: https://github.com/cosmos/cosmos-rust/pull/215
> cosmos-sdk-proto v0.12.0

- cosmrs/CHANGELOG.md
- cosmrs/Cargo.toml
- Bump tendermint-rs crates to v0.23.7 ([#215])
- Bump `prost` to v0.10 ([#215])
- Bump `tonic` to v0.7 ([#215])
- Bump `cosmos-sdk-proto` to v0.12.0 ([#217])
[#215]: https://github.com/cosmos/cosmos-rust/pull/215
[#217]: https://github.com/cosmos/cosmos-rust/pull/217
> cosmrs v0.7.0

- cosmos-sdk-proto/CHANGELOG.md
v0.12.1 fixes #219, which is a major bug. See #220.
> cosmos-sdk-proto: yank v0.12.0

- .github/workflows/cosmos-sdk-proto.yml
- cosmos-sdk-proto/Cargo.toml
- cosmos-sdk-proto/src/prost/cosmos-sdk/cosmos.auth.v1beta1.rs
- cosmos-sdk-proto/src/prost/cosmos-sdk/cosmos.authz.v1beta1.rs
- cosmos-sdk-proto/src/prost/cosmos-sdk/cosmos.bank.v1beta1.rs
- cosmos-sdk-proto/src/prost/cosmos-sdk/cosmos.base.reflection.v1beta1.rs
- cosmos-sdk-proto/src/prost/cosmos-sdk/cosmos.base.reflection.v2alpha1.rs
- cosmos-sdk-proto/src/prost/cosmos-sdk/cosmos.base.tendermint.v1beta1.rs
- cosmos-sdk-proto/src/prost/cosmos-sdk/cosmos.crisis.v1beta1.rs
- cosmos-sdk-proto/src/prost/cosmos-sdk/cosmos.distribution.v1beta1.rs
- cosmos-sdk-proto/src/prost/cosmos-sdk/cosmos.evidence.v1beta1.rs
- cosmos-sdk-proto/src/prost/cosmos-sdk/cosmos.feegrant.v1beta1.rs
- cosmos-sdk-proto/src/prost/cosmos-sdk/cosmos.gov.v1beta1.rs
- cosmos-sdk-proto/src/prost/cosmos-sdk/cosmos.mint.v1beta1.rs
- cosmos-sdk-proto/src/prost/cosmos-sdk/cosmos.params.v1beta1.rs
- cosmos-sdk-proto/src/prost/cosmos-sdk/cosmos.slashing.v1beta1.rs
- cosmos-sdk-proto/src/prost/cosmos-sdk/cosmos.staking.v1beta1.rs
- cosmos-sdk-proto/src/prost/cosmos-sdk/cosmos.tx.v1beta1.rs
- cosmos-sdk-proto/src/prost/cosmos-sdk/cosmos.upgrade.v1beta1.rs
- cosmos-sdk-proto/src/prost/cosmos-sdk/cosmos.vesting.v1beta1.rs
- cosmos-sdk-proto/src/prost/ibc-go/ibc.applications.interchain_accounts.controller.v1.rs
- cosmos-sdk-proto/src/prost/ibc-go/ibc.applications.interchain_accounts.host.v1.rs
- cosmos-sdk-proto/src/prost/ibc-go/ibc.applications.interchain_accounts.v1.rs
- cosmos-sdk-proto/src/prost/ibc-go/ibc.applications.transfer.v1.rs
- cosmos-sdk-proto/src/prost/ibc-go/ibc.core.channel.v1.rs
- cosmos-sdk-proto/src/prost/ibc-go/ibc.core.client.v1.rs
- cosmos-sdk-proto/src/prost/ibc-go/ibc.core.connection.v1.rs
- cosmos-sdk-proto/src/prost/wasmd/cosmwasm.wasm.v1.rs
- proto-build/src/main.rs
Closes #226
Adds an on-by-default `grpc-transport` feature which enables the corresponding `transport` feature in `tonic`. The main use case is supporting gRPC in WASM environments.
To make this work with generated code, the generated protos are patched to feature-gate the `tonic::transport`-dependent code.
> cosmos-sdk-protos: add `grpc-transport` feature

- cosmos-sdk-proto/CHANGELOG.md
- cosmos-sdk-proto/Cargo.toml
- `grpc-transport` crate feature ([#230])
[#230]: https://github.com/cosmos/cosmos-rust/pull/230
> cosmos-sdk-proto v0.12.2

- .github/workflows/cosmrs.yml
- cosmos-sdk-proto/src/lib.rs
- cosmrs/src/dev.rs
- cosmrs/src/error.rs
- cosmrs/src/lib.rs
Enables the following lints:
- `clippy::checked_conversions`
- `clippy::panic`
- `clippy::panic_in_result_fn`
- `clippy::unwrap_used`
- `missing_docs`
- `trivial_casts`
- `trivial_numeric_casts`
- `rust_2018_idioms`
- `unused_lifetimes`
- `unused_import_braces`
Also adds a `doc` job in CI that tests that rustdoc builds successfully without warnings.
> cosmrs: enable more lints and test rustdoc in CI

- cosmrs/src/abci.rs
- cosmrs/src/auth.rs
- cosmrs/src/cosmwasm.rs
- cosmrs/src/lib.rs
- cosmrs/src/tx/msg.rs
- cosmrs/src/vesting.rs
Hi!
I've added additional concrete types for things we already had defined in protobuf files, in particular `Response` types for various `cosmwasm` requests. But also for `MsgData` and `TxMsgData` from `abci`, for which I created a separate module in `cosmrs` crate. I was not entirely sure whether this was  the most appropriate place for it.
From the interesting bits, I've added the following bit to `MsgData` and `TxMsgData`:
```rust
impl MsgData {
pub fn try_decode_as<M: Msg>(&self) -> Result<M> {
M::Proto::decode(&*self.data)?.try_into()
}
}
impl TryFrom<tendermint::abci::Data> for TxMsgData {
type Error = ErrorReport;
fn try_from(data: tendermint::abci::Data) -> Result<TxMsgData> {
let proto = proto::cosmos::base::abci::v1beta1::TxMsgData::decode(data.value().as_ref())?; …
```
> Additional protobuf-equivalent types

- cosmrs/src/crypto/secp256k1/signing_key.rs
Fixes #242 
Implementing this fix allowed my crate to build.
Also, units tests using this function to derive private keys and then known addresses ([local testnet](https://docs.scrt.network/dev/LocalSecret.html#accounts)) now pass.
> Remove unneeded type parameter in SigningKey::derive_from_path

- cosmos-sdk-proto/CHANGELOG.md
- cosmos-sdk-proto/Cargo.toml
- Additional `cosmwasm` protos ([#240], [#244])
[#240]: https://github.com/cosmos/cosmos-rust/pull/240
[#244]: https://github.com/cosmos/cosmos-rust/pull/244
> cosmos-sdk-proto v0.12.3

- cosmrs/CHANGELOG.md
- cosmrs/Cargo.toml
- `abci`, `auth`, `cosmwasm`, and `vesting` type wrappers ([#234])
- `bank::MsgMultiSend` support ([#237])
- Remove unneeded generic type parameter to `SigningKey::derive_from_path` ([#243])
[#234]: https://github.com/cosmos/cosmos-rust/pull/234
[#237]: https://github.com/cosmos/cosmos-rust/pull/237
[#243]: https://github.com/cosmos/cosmos-rust/pull/243
> cosmrs v0.7.1

- cosmos-sdk-proto/Cargo.toml
- cosmrs/Cargo.toml
NOTE: work-in-progress, sources 0.23.8-pre.1 from git
This includes the following additional dependency upgrades:
- `k256` v0.11
- `ecdsa` v0.14
> Bump tendermint-rs crates to v0.23.8

- cosmrs/src/lib.rs
The re-exports CosmRS provides are easily overlooked, and many downstream users explicitly include `cosmrs`, `cosmos-sdk-proto`, and `tendermint` in their Cargo.toml.
This documentation should help steer people towards using the re-exports.
> cosmrs: document re-exports

- cosmrs/Cargo.toml
Transitively enables gRPC support in `cosmos-sdk-proto`
> cosmrs: add `grpc` features

- cosmos-sdk-proto/CHANGELOG.md
- cosmos-sdk-proto/Cargo.toml
- cosmrs/Cargo.toml
- gRPC server definitions ([#249])
- Protobuf traits originally from `cosmrs` ([#255])
- Bump `tendermint-proto` to v0.23.8 ([#253])
[#249]: https://github.com/cosmos/cosmos-rust/pull/249
[#253]: https://github.com/cosmos/cosmos-rust/pull/253
[#255]: https://github.com/cosmos/cosmos-rust/pull/255
> cosmos-sdk-proto v0.13.0

- cosmrs/CHANGELOG.md
- cosmrs/Cargo.toml
- cosmrs/src/base.rs
- `feegrant` module support ([#250])
- `grpc` features ([#258])
- Changed internal `Coin` representation to `u128` ([#235])
- Implemented `serde` traits for `Denom` ([#235])
- Bump `k256` to v0.11 ([#253])
- Bump tendermint-rs crates to v0.23.8 ([#253])
- Move protobuf traits from `cosmrs` => `cosmos-sdk-proto` ([#255])
- MSRV 1.57 ([#257])
- Bump `cosmos-sdk-proto` to v0.13.0 ([#260])
- Visibility on `cosmwasm::ContractInfo` ([#247])
- `Decimal` type ([#235])
[#235]: https://github.com/cosmos/cosmos-rust/pull/235
[#247]: https://github.com/cosmos/cosmos-rust/pull/247
[#250]: https://github.com/cosmos/cosmos-rust/pull/250
[#253]: https://github.com/cosmos/cosmos-rust/pull/253
[#255]: https://github.com/cosmos/cosmos-rust/pull/255
[#257]: https://github.com/cosmos/cosmos-rust/pull/257 …
> cosmrs v0.8.0

- cosmos-sdk-proto/src/lib.rs
This module contains only trait impls and is therefore empty. It was mistakenly made `pub`.
> cosmos-sdk-proto: remove `pub` from `mod type_urls`

- cosmos-sdk-proto/src/prost/cosmos-sdk/cosmos.staking.v1beta1.rs
- proto-build/src/main.rs
The prost-generated `stake_authorization` module contains clashing `struct Validators` and `enum Validators` owning to a `oneof` on a field named `validators`. See #154.
We've been patching this by hand for quite some time, and this PR finally automates the process, implementing the solution suggested upstream at cosmos/cosmos-sdk#12316:
- Renames `enum Validators` to `enum Policy`(formerly `IsStakeAuthorizationValidators`)
- Retains `struct Validators` as-is, as this matches the `message` defined in the schema.
> cosmos-sdk-proto: fix type name clash in cosmos.staking.v1beta1.rs

- .github/workflows/rebuild-protos.yml
`prost-build` now requires `protoc` as a hard dependency as of v0.11
> CI: install `protoc` within `rebuild-protos` workflow

- cosmrs/src/error.rs
- cosmrs/src/tx.rs
- cosmrs/src/tx/body.rs
- cosmrs/src/tx/builder.rs
- cosmrs/tests/integration.rs
Adds a builder type for constructing `tx::Body`.
> cosmrs: add `tx::BodyBuilder`

- cosmrs/src/feegrant.rs
Adds the domain types originally from #250 (removed in f63ded6) which were previously blocked on #252.
cc @neacsu
> cosmrs: add additional `feegrant` domain types

- cosmrs/src/base.rs
> cosmrs: allow alphanumeric Bech32 prefixes on `AccountId`

- cosmrs/Cargo.toml
- cosmrs/src/abci.rs
- cosmrs/src/crypto/legacy_amino.rs
- cosmrs/src/feegrant.rs
- cosmrs/src/lib.rs
- cosmrs/src/tx.rs
- cosmrs/src/tx/raw.rs
Accesses types/traits indirectly via `cosmos-sdk-proto` instead.
> cosmrs: remove direct dependencies on `prost`

- cosmos-sdk-proto/CHANGELOG.md
- cosmos-sdk-proto/Cargo.toml
- cosmos-sdk-proto/README.md
- cosmrs/Cargo.toml
- Rename `cosmos::staking::v1beta1::IsStakeAuthroizationValidator` to `::Policy` ([#275])
- Bump `prost` to v0.11 ([#277])
- Bump `tendermint-proto` to v0.23.9 ([#277])
- Bump `tonic` to v0.8 ([#277])
- `pub` from `mod type_urls` ([#263])
[#263]: https://github.com/cosmos/cosmos-rust/pull/263
[#275]: https://github.com/cosmos/cosmos-rust/pull/275
[#277]: https://github.com/cosmos/cosmos-rust/pull/277
> cosmos-sdk-proto v0.14.0

- cosmrs/CHANGELOG.md
- cosmrs/Cargo.toml
- `tx::BodyBuilder` ([#254])
- Additional `feegrant` domain types ([#280])
- Allow alphanumeric Bech32 prefixes on `AccountId` ([#281])
- Bump tendermint-rs crates to v0.23.9 ([#277])
- Bump `cosmos-sdk-proto` to v0.14 ([#283])
- Direct dependencies on `prost` ([#282])
[#254]: https://github.com/cosmos/cosmos-rust/pull/254
[#277]: https://github.com/cosmos/cosmos-rust/pull/277
[#280]: https://github.com/cosmos/cosmos-rust/pull/280
[#281]: https://github.com/cosmos/cosmos-rust/pull/281
[#282]: https://github.com/cosmos/cosmos-rust/pull/282
[#283]: https://github.com/cosmos/cosmos-rust/pull/283
> cosmrs v0.9.0

- cosmos-sdk-proto/src/type_urls.rs
> impl TypeUrl for MsgTransfer

- cosmrs/src/base.rs
All of the cosmos-sdk proto types use Strings for the account addresses: [ex](https://github.com/cosmos/cosmos-rust/blob/main/cosmos-sdk-proto/src/prost/cosmos-sdk/cosmos.bank.v1beta1.rs#L429). 
I know there is the `AsRef<str>` and `fmt::Display` impls, but I wanted a way to move the bech32 String out of the AccountId instead of having to allocate a new String each time.
Let me know if you think there's a better way.
> Allow bech32 String to be moved out of AccountId

- cosmos-sdk-proto/CHANGELOG.md
- cosmos-sdk-proto/Cargo.toml
- cosmrs/Cargo.toml
- `TypeUrl` impl for auth accounts ([#285])
- `TypeUrl` impl for `MsgTransfer` ([#296])
- Bump `tendermint-proto` to v0.26; MSRV 1.59 ([#302])
[#285]: https://github.com/cosmos/cosmos-rust/pull/285
[#296]: https://github.com/cosmos/cosmos-rust/pull/296
[#302]: https://github.com/cosmos/cosmos-rust/pull/302
> cosmos-sdk-proto v0.15.0

- cosmrs/CHANGELOG.md
- cosmrs/Cargo.toml
- `Coin` constructor ([#291])
- Impl `From<AccountId>` for `String` ([#301])
- Bump tendermint-rs crates to v0.26; MSRV 1.59 ([#302])
- Refactor into submodules ([#303])
- Bump `cosmos-sdk-proto` to v0.15 ([#304])
[#291]: https://github.com/cosmos/cosmos-rust/pull/291
[#301]: https://github.com/cosmos/cosmos-rust/pull/301
[#302]: https://github.com/cosmos/cosmos-rust/pull/302
[#303]: https://github.com/cosmos/cosmos-rust/pull/303
[#304]: https://github.com/cosmos/cosmos-rust/pull/304
> cosmrs v0.10.0

- cosmos-sdk-proto/CHANGELOG.md
- cosmos-sdk-proto/Cargo.toml
- cosmrs/Cargo.toml
- Bump tendermint-rs crates to 0.27 ([#306])
[#306]: https://github.com/cosmos/cosmos-rust/pull/306
> cosmos-sdk-proto v0.16.0

- cosmrs/CHANGELOG.md
- cosmrs/Cargo.toml
- Bump tendermint-rs crates to 0.27 ([#306])
- Bump `cosmos-sdk-proto` to v0.16 ([#307])
[#306]: https://github.com/cosmos/cosmos-rust/pull/306
[#307]: https://github.com/cosmos/cosmos-rust/pull/307
> cosmrs v0.11.0

- cosmrs/src/cosmwasm.rs
This PR exposes `MsgMigrateContract` and `MsgMigrateContractResponse`.
> Expose `cosmwasm::msg_migrate_contract` structs

- Cargo.lock
- cosmos-sdk-proto/CHANGELOG.md
- cosmos-sdk-proto/Cargo.toml
- cosmrs/Cargo.toml
- Support for `wasmd` >=0.29 by generating files via buf ([#358])
- Bump tendermint-rs crates to 0.30 ([#354])
- MSRV 1.63 ([#356])
[#354]: https://github.com/cosmos/cosmos-rust/pull/354
[#356]: https://github.com/cosmos/cosmos-rust/pull/356
[#358]: https://github.com/cosmos/cosmos-rust/pull/358
> cosmos-sdk-proto v0.17.0

- Cargo.lock
- cosmrs/CHANGELOG.md
- cosmrs/Cargo.toml
- Expose `cosmwasm::msg_migrate_contract` structs ([#315])
- Bump tendermint-rs crates to 0.30 ([#354])
- MSRV 1.63 ([#356])
- Support for `wasmd` >=0.29 by generating files via `buf` ([#358])
- Bump `cosmos-sdk-proto` to v0.17 ([#367])
[#315]: https://github.com/cosmos/cosmos-rust/pull/315
[#354]: https://github.com/cosmos/cosmos-rust/pull/354
[#356]: https://github.com/cosmos/cosmos-rust/pull/356
[#358]: https://github.com/cosmos/cosmos-rust/pull/358
[#367]: https://github.com/cosmos/cosmos-rust/pull/367
> cosmrs v0.12.0

- Cargo.lock
- cosmos-sdk-proto/CHANGELOG.md
- cosmos-sdk-proto/Cargo.toml
- cosmrs/Cargo.toml
- TypeUrl for missing proposal types as well as others ([#360])
- TypeUrl for some of structs from /cosmos.tx.v1beta1 namespace ([#384])
- Bump `tendermint-proto` to v0.31 ([#385])
- Bump `tonic` to v0.9 ([#386])
[#360]: https://github.com/cosmos/cosmos-rust/pull/360
[#384]: https://github.com/cosmos/cosmos-rust/pull/384
[#385]: https://github.com/cosmos/cosmos-rust/pull/385
[#386]: https://github.com/cosmos/cosmos-rust/pull/386
> cosmos-sdk-proto v0.18.0

- Cargo.lock
- cosmrs/CHANGELOG.md
- cosmrs/Cargo.toml
- Bump signature + tendermint-rs dependencies; MSRV 1.65 ([#385])
- `bip32` v0.5
- `ecdsa` v0.16
- `k256` v0.13
- `tendermint` v0.31
- `tendermint-proto` v0.31
- `tendermint-rpc` v0.31
- Bump `cosmos-sdk-proto` to v0.18 ([#390])
[#385]: https://github.com/cosmos/cosmos-rust/pull/385
[#390]: https://github.com/cosmos/cosmos-rust/pull/390
> cosmrs v0.13.0

- Cargo.lock
- cosmos-sdk-proto/Cargo.toml
- cosmrs/Cargo.toml
Prerelease which includes #395: bump `COSMOS_SDK_REV` to v0.46.12
> cosmos-sdk-proto v0.19.0-pre.0

- Cargo.lock
- cosmos-sdk-proto/CHANGELOG.md
- cosmos-sdk-proto/Cargo.toml
- cosmrs/Cargo.toml
- Use `buf` to generate Cosmos SDK protos ([#393])
- Bump `COSMOS_SDK_REV` to v0.46.12 ([#395])
- Bump `tendermint-proto` to v0.32 ([#400])
[#393]: https://github.com/cosmos/cosmos-rust/pull/393
[#395]: https://github.com/cosmos/cosmos-rust/pull/395
[#400]: https://github.com/cosmos/cosmos-rust/pull/400
> cosmos-sdk-proto v0.19.0

- Cargo.lock
- cosmrs/CHANGELOG.md
- cosmrs/Cargo.toml
- Bump `tendermint`/`tendermint-rpc` to v0.32 ([#400])
- Bump `cosmos-sdk-proto` to v0.19 ([#401])
[#400]: https://github.com/cosmos/cosmos-rust/pull/400
[#401]: https://github.com/cosmos/cosmos-rust/pull/401
> cosmrs v0.14.0

- cosmos-sdk-proto/src/prost/cosmos-sdk/cosmos.app.v1alpha1.tonic.rs
- cosmos-sdk-proto/src/prost/cosmos-sdk/cosmos.auth.v1beta1.tonic.rs
- cosmos-sdk-proto/src/prost/cosmos-sdk/cosmos.authz.v1beta1.tonic.rs
- cosmos-sdk-proto/src/prost/cosmos-sdk/cosmos.bank.v1beta1.tonic.rs
- cosmos-sdk-proto/src/prost/cosmos-sdk/cosmos.base.node.v1beta1.tonic.rs
- cosmos-sdk-proto/src/prost/cosmos-sdk/cosmos.base.reflection.v1beta1.tonic.rs
- cosmos-sdk-proto/src/prost/cosmos-sdk/cosmos.base.reflection.v2alpha1.tonic.rs
- cosmos-sdk-proto/src/prost/cosmos-sdk/cosmos.base.tendermint.v1beta1.tonic.rs
- cosmos-sdk-proto/src/prost/cosmos-sdk/cosmos.crisis.v1beta1.tonic.rs
- cosmos-sdk-proto/src/prost/cosmos-sdk/cosmos.distribution.v1beta1.tonic.rs
- cosmos-sdk-proto/src/prost/cosmos-sdk/cosmos.evidence.v1beta1.tonic.rs
- cosmos-sdk-proto/src/prost/cosmos-sdk/cosmos.feegrant.v1beta1.tonic.rs
- cosmos-sdk-proto/src/prost/cosmos-sdk/cosmos.gov.v1.tonic.rs
- cosmos-sdk-proto/src/prost/cosmos-sdk/cosmos.gov.v1beta1.tonic.rs
- cosmos-sdk-proto/src/prost/cosmos-sdk/cosmos.group.v1.tonic.rs
- cosmos-sdk-proto/src/prost/cosmos-sdk/cosmos.mint.v1beta1.tonic.rs
- cosmos-sdk-proto/src/prost/cosmos-sdk/cosmos.nft.v1beta1.tonic.rs
- cosmos-sdk-proto/src/prost/cosmos-sdk/cosmos.params.v1beta1.tonic.rs
- cosmos-sdk-proto/src/prost/cosmos-sdk/cosmos.slashing.v1beta1.tonic.rs
- cosmos-sdk-proto/src/prost/cosmos-sdk/cosmos.staking.v1beta1.tonic.rs
- cosmos-sdk-proto/src/prost/cosmos-sdk/cosmos.tx.v1beta1.tonic.rs
- cosmos-sdk-proto/src/prost/cosmos-sdk/cosmos.upgrade.v1beta1.tonic.rs
- cosmos-sdk-proto/src/prost/cosmos-sdk/cosmos.vesting.v1beta1.tonic.rs
- proto-build/buf.sdk.gen.yaml
- proto-build/buf.wasmd.gen.yaml
The old `buf` plugin we were using is now 404.
Closes #427
~~NOTE: running into an error with the tonic plugin:~~
Fixed by downgrading to older versions of the plugin.
> proto-build: migrate to neoeinstein-prost/tonic

- cosmos-sdk-proto/src/prost/cosmos-sdk/cosmos.app.v1alpha1.tonic.rs
- cosmos-sdk-proto/src/prost/cosmos-sdk/cosmos.auth.v1beta1.tonic.rs
- cosmos-sdk-proto/src/prost/cosmos-sdk/cosmos.authz.v1beta1.tonic.rs
- cosmos-sdk-proto/src/prost/cosmos-sdk/cosmos.bank.v1beta1.tonic.rs
- cosmos-sdk-proto/src/prost/cosmos-sdk/cosmos.base.node.v1beta1.tonic.rs
- cosmos-sdk-proto/src/prost/cosmos-sdk/cosmos.base.reflection.v1beta1.tonic.rs
- cosmos-sdk-proto/src/prost/cosmos-sdk/cosmos.base.reflection.v2alpha1.tonic.rs
- cosmos-sdk-proto/src/prost/cosmos-sdk/cosmos.base.tendermint.v1beta1.tonic.rs
- cosmos-sdk-proto/src/prost/cosmos-sdk/cosmos.crisis.v1beta1.tonic.rs
- cosmos-sdk-proto/src/prost/cosmos-sdk/cosmos.distribution.v1beta1.tonic.rs
- cosmos-sdk-proto/src/prost/cosmos-sdk/cosmos.evidence.v1beta1.tonic.rs
- cosmos-sdk-proto/src/prost/cosmos-sdk/cosmos.feegrant.v1beta1.tonic.rs
- cosmos-sdk-proto/src/prost/cosmos-sdk/cosmos.gov.v1.tonic.rs
- cosmos-sdk-proto/src/prost/cosmos-sdk/cosmos.gov.v1beta1.tonic.rs
- cosmos-sdk-proto/src/prost/cosmos-sdk/cosmos.group.v1.tonic.rs
- cosmos-sdk-proto/src/prost/cosmos-sdk/cosmos.mint.v1beta1.tonic.rs
- cosmos-sdk-proto/src/prost/cosmos-sdk/cosmos.nft.v1beta1.tonic.rs
- cosmos-sdk-proto/src/prost/cosmos-sdk/cosmos.params.v1beta1.tonic.rs
- cosmos-sdk-proto/src/prost/cosmos-sdk/cosmos.slashing.v1beta1.tonic.rs
- cosmos-sdk-proto/src/prost/cosmos-sdk/cosmos.staking.v1beta1.tonic.rs
- cosmos-sdk-proto/src/prost/cosmos-sdk/cosmos.tx.v1beta1.tonic.rs
- cosmos-sdk-proto/src/prost/cosmos-sdk/cosmos.upgrade.v1beta1.tonic.rs
- cosmos-sdk-proto/src/prost/cosmos-sdk/cosmos.vesting.v1beta1.tonic.rs
- cosmos-sdk-proto/src/prost/wasmd/cosmwasm.wasm.v1.tonic.rs
- proto-build/buf.sdk.gen.yaml
- proto-build/buf.wasmd.gen.yaml
Updates to the latest version of `protoc-gen-tonic`.
> proto-build: bump neoeinstein-tonic to v0.3.0

- Cargo.lock
- cosmos-sdk-proto/Cargo.toml
- cosmos-sdk-proto/src/prost/cosmos-sdk/cosmos.base.abci.v1beta1.rs
- cosmos-sdk-proto/src/prost/cosmos-sdk/cosmos.base.store.v1beta1.rs
- cosmos-sdk-proto/src/prost/cosmos-sdk/cosmos.base.tendermint.v1beta1.rs
- cosmos-sdk-proto/src/prost/cosmos-sdk/cosmos.staking.v1beta1.rs
- cosmos-sdk-proto/src/prost/cosmos-sdk/cosmos.tx.v1beta1.rs
- cosmos-sdk-proto/src/prost/ibc-go/ibc.applications.transfer.v1.rs
- cosmos-sdk-proto/src/prost/ibc-go/ibc.lightclients.tendermint.v1.rs
- cosmos-sdk-proto/src/prost/ibc-go/ics23.rs
- cosmrs/Cargo.toml
- cosmrs/src/cosmwasm/access_config.rs
- cosmrs/src/cosmwasm/contract_code_history_entry.rs
- cosmrs/tests/integration.rs
- proto-build/Cargo.toml
- proto-build/buf.sdk.gen.yaml
This additionally bumps `prost` to v0.12 and `tonic` to v0.10.
This release is the first we've used with tendermint-rs multi-version support, which for now we've also pinned to (upstream) Tendermint v0.34.
> Bump tendermint-rs dependencies to v0.34

- .github/workflows/cosmrs.yml
- Cargo.lock
- cosmrs/Cargo.toml
- cosmrs/src/crypto/secp256k1/signing_key.rs
- cosmrs/src/tx.rs
Enables support for using CosmRS in environments unsupported by `getrandom`, like non-JS WASM environments.
Fixes #407
> cosmrs: add `getrandom` feature

- Cargo.lock
- cosmrs/Cargo.toml
- cosmrs/src/crypto/secp256k1/signing_key.rs
Followup from #434 which enables `ecdsa/std` and uses eyre's built-in `Error`-trait based error propagation.
> cosmrs: error handling cleanup

- cosmrs/src/crypto/secp256k1/signing_key.rs
This trait is necessary for using through async functions.
> feat: add sendable on secp256k1 signing key

- cosmos-sdk-proto/src/lib.rs
> cosmos-sdk-proto: expose `gov::v1` module

- Cargo.lock
- cosmos-sdk-proto/CHANGELOG.md
- cosmos-sdk-proto/Cargo.toml
- cosmrs/Cargo.toml
- Expose `gov::v1` module ([#437])
- Migrate to `neoeinstein-prost`/`neoeinstein-tonic` ([#429])
- Bump `tendermint-proto` dependency to v0.34 ([#431])
- Replace `TypeUrl` trait with `prost::Name` trait ([#432])
- Bump `COSMOS_SDK_REV` to v0.46.15 ([#439])
[#429]: https://github.com/cosmos/cosmos-rust/pull/429
[#431]: https://github.com/cosmos/cosmos-rust/pull/431
[#432]: https://github.com/cosmos/cosmos-rust/pull/432
[#437]: https://github.com/cosmos/cosmos-rust/pull/437
[#439]: https://github.com/cosmos/cosmos-rust/pull/439
> cosmos-sdk-proto v0.20.0

- Cargo.lock
- README.md
- cosmos-sdk-proto/CHANGELOG.md
- cosmos-sdk-proto/Cargo.toml
- cosmos-sdk-proto/README.md
- cosmrs/CHANGELOG.md
- cosmrs/Cargo.toml
- cosmrs/README.md
- Export `msg_clear_admin` and `msg_update_admin` types ([#419])
- `getrandom` feature ([#434])
- Bound `EcdsaSigner` trait on `Sync + Send` ([#410])
- MSRV 1.72 ([#428])
- Bump `tendermint`/`tendermint-rpc` dependencies to v0.34 ([#431])
- Replace `TypeUrl` with `Name` trait ([#432])
- Bump `cosmos-sdk-proto` to v0.20 ([#440])
- `PublicKey::to_any` ([#406])
[#406]: https://github.com/cosmos/cosmos-rust/pull/406
[#410]: https://github.com/cosmos/cosmos-rust/pull/410
[#419]: https://github.com/cosmos/cosmos-rust/pull/419
[#428]: https://github.com/cosmos/cosmos-rust/pull/428
[#431]: https://github.com/cosmos/cosmos-rust/pull/431
[#432]: https://github.com/cosmos/cosmos-rust/pull/432
[#434]: https://github.com/cosmos/cosmos-rust/pull/434
[#440]: …
> cosmrs v0.15.0

- cosmrs/src/base/account_id.rs
Small fix to allow uppercase bech32 which you can see at https://www.mintscan.io/stargaze/tx/B198B9778B0873752E37F854C4BDEE6523C47EA10F1B9C12B671A9782FF3E0DE?height=4891489
> Add support for uppercase bech32

- cosmos-sdk-proto/src/lib.rs
- cosmos-sdk-proto/src/type_names.rs
- cosmrs/src/base.rs
- cosmrs/src/base/query.rs
- cosmrs/src/base/query/pagination.rs
- cosmrs/src/lib.rs
- cosmrs/src/slashing.rs
- cosmrs/src/slashing/genesis_state.rs
- cosmrs/src/slashing/missed_block.rs
- cosmrs/src/slashing/msg_unjail.rs
- cosmrs/src/slashing/params.rs
- cosmrs/src/slashing/query_params_request.rs
- cosmrs/src/slashing/query_params_response.rs
- cosmrs/src/slashing/query_signing_info_request.rs
- cosmrs/src/slashing/query_signing_info_response.rs
- cosmrs/src/slashing/query_signing_infos_request.rs
- cosmrs/src/slashing/query_signing_infos_response.rs
- cosmrs/src/slashing/signing_info.rs
- cosmrs/src/slashing/validator_missed_blocks.rs
- cosmrs/src/slashing/validator_signing_info.rs
this PR introduces support for the slashing module
> added support for slashing module

- cosmos-sdk-proto/src/type_names.rs
- cosmrs/src/error.rs
Adding a few missing type names implementations.
> Add more IBC related names

- cosmos-sdk-proto/src/type_names.rs
- cosmrs/src/staking.rs
- cosmrs/src/staking/commission.rs
- cosmrs/src/staking/commission_rates.rs
- cosmrs/src/staking/description.rs
- cosmrs/src/staking/historical_info.rs
- cosmrs/src/staking/query_historical_info_request.rs
- cosmrs/src/staking/query_historical_info_response.rs
- cosmrs/src/staking/query_validator_request.rs
- cosmrs/src/staking/query_validator_response.rs
- cosmrs/src/staking/query_validators_request.rs
- cosmrs/src/staking/query_validators_response.rs
- cosmrs/src/staking/validator.rs
this PR extends the functionality of the staking module by adding support for types needed in validators-related queries
> added support for validator-related queries in staking module

- cosmrs/src/cosmwasm/contract_code_history_entry.rs
a simple bugfix to `ContractCodeHistoryEntry` type. Rather then using default values of `None` and `vec![]` for `updated` and `msg` respectively, parse those fields out of the protobuf response instead
> bugfix: ContractCodeHistoryEntry populate 'updated' and 'msg' fields from proto data

- Cargo.lock
- cosmos-sdk-proto/CHANGELOG.md
- cosmos-sdk-proto/Cargo.toml
- proto-build/Cargo.toml
- Update `tonic` to v0.11
This is a breaking change to _cosmos-sdk-proto_.
> cosmos-sdk-proto: update tonic to 0.11

- Cargo.lock
- cosmos-sdk-proto/Cargo.toml
- cosmos-sdk-proto/src/prost/ibc-go/cosmos.auth.v1beta1.rs
- cosmos-sdk-proto/src/prost/ibc-go/cosmos.base.query.v1beta1.rs
- cosmos-sdk-proto/src/prost/ibc-go/cosmos.base.v1beta1.rs
- cosmos-sdk-proto/src/prost/ibc-go/cosmos.upgrade.v1beta1.rs
- cosmos-sdk-proto/src/prost/ibc-go/ibc.applications.interchain_accounts.controller.v1.rs
- cosmos-sdk-proto/src/prost/ibc-go/ibc.applications.interchain_accounts.host.v1.rs
- cosmos-sdk-proto/src/prost/ibc-go/ibc.applications.interchain_accounts.v1.rs
- cosmos-sdk-proto/src/prost/ibc-go/ibc.applications.transfer.v1.rs
- cosmos-sdk-proto/src/prost/ibc-go/ibc.applications.transfer.v2.rs
- cosmos-sdk-proto/src/prost/ibc-go/ibc.core.channel.v1.rs
- cosmos-sdk-proto/src/prost/ibc-go/ibc.core.client.v1.rs
- cosmos-sdk-proto/src/prost/ibc-go/ibc.core.commitment.v1.rs
- cosmos-sdk-proto/src/prost/ibc-go/ibc.core.connection.v1.rs
- cosmos-sdk-proto/src/prost/ibc-go/ibc.core.types.v1.rs
- cosmos-sdk-proto/src/prost/ibc-go/ibc.lightclients.localhost.v1.rs
- cosmos-sdk-proto/src/prost/ibc-go/ibc.lightclients.solomachine.v1.rs
- cosmos-sdk-proto/src/prost/ibc-go/ibc.lightclients.solomachine.v2.rs
- cosmos-sdk-proto/src/prost/ibc-go/ibc.lightclients.tendermint.v1.rs
- cosmos-sdk-proto/src/prost/ibc-go/ics23.rs
- cosmos-sdk-proto/src/type_names.rs
- proto-build/Cargo.toml
- proto-build/src/main.rs
Uses the recently added support in `prost-build` for automatically generating impls of the `Name` trait for IBC-related types, rather than maintaining them by hand in the `type_names` module.
Unfortunately we can only do this for the IBC protos, since we build the others using `buf`.
> cosmos-sdk-proto: use `prost-build` to generate IBC `Name` impls

- Cargo.lock
- cosmos-sdk-proto/CHANGELOG.md
- cosmos-sdk-proto/Cargo.toml
- cosmrs/Cargo.toml
- Update `tonic` to v0.11 ([#460])
- Bump `tendermint-proto` dependency to v0.35 ([#461])
- Use `prost-build` to generate IBC `Name` impls ([#462])
[#460]: https://github.com/cosmos/cosmos-rust/pull/460
[#461]: https://github.com/cosmos/cosmos-rust/pull/461
[#462]: https://github.com/cosmos/cosmos-rust/pull/462
> cosmos-sdk-proto v0.21.0

- Cargo.lock
- cosmrs/CHANGELOG.md
- cosmrs/Cargo.toml
- Support for uppercase Bech32 ([#444])
- Support for `slashing` module ([#452])
- Support for validator-related queries in `staking` module ([#453])
- Expose `base::query` module and pagination types ([#454])
- Bump `tendermint`/`tendermint-rpc` dependencies to v0.35 ([#461])
- Bump `cosmos-sdk-proto` to v0.21.0 ([#463])
- Correctly populate `updated` and `msg` fields from proto responses ([#451])
[#444]: https://github.com/cosmos/cosmos-rust/pull/444
[#451]: https://github.com/cosmos/cosmos-rust/pull/451
[#452]: https://github.com/cosmos/cosmos-rust/pull/452
[#453]: https://github.com/cosmos/cosmos-rust/pull/453
[#454]: https://github.com/cosmos/cosmos-rust/pull/454
[#461]: https://github.com/cosmos/cosmos-rust/pull/461
[#463]: https://github.com/cosmos/cosmos-rust/pull/463
> cosmrs v0.16.0

- Cargo.lock
- cosmos-sdk-proto/CHANGELOG.md
- cosmos-sdk-proto/Cargo.toml
- Deprecated `MessageExt` methods: missed from v0.21.0, technically a breaking change, but the just-published v0.21.0 release will be yanked ([#465])
[#465]: https://github.com/cosmos/cosmos-rust/pull/465
> cosmos-sdk-proto v0.21.1

- cosmrs/src/base/denom.rs
This PR aims at updating cosmrs to handle all valid coin denoms
With token factory modules, denoms are more diverse than before.
Denom validation must follow
Here is the Cosmos sdk coin validation function 
https://github.com/cosmos/cosmos-sdk/blob/94338e516d6fd095fdca175b47d87bd9020e7740/types/coin.go#L890
> Update denom validation

- cosmrs/src/base/denom.rs
Implements the same checks as the upstream Cosmos SDK's `MatchDenom`:
https://github.com/cosmos/cosmos-sdk/blob/6a07568/types/coin.go#L885-L906
> cosmrs: match upstream Cosmos SDK's Denom validation logic

- Cargo.lock
- cosmos-sdk-proto/CHANGELOG.md
- cosmos-sdk-proto/Cargo.toml
- cosmrs/Cargo.toml
- Bump `tendermint-proto` dependency to v0.37 ([#469])
[#469]: https://github.com/cosmos/cosmos-rust/pull/469
> cosmos-sdk-proto v0.22.0

- Cargo.lock
- cosmrs/CHANGELOG.md
- cosmrs/Cargo.toml
- Basic parsing of `msg_responses` field inside `TxMsgData` ([#472])
- Bump tendermint-rs dependencies to v0.37 ([#469])
- Match upstream Cosmos SDK's Denom validation logic ([#468], [#470])
- Bump `cosmos-sdk-proto` to v0.22 ([#473])
[#468]: https://github.com/cosmos/cosmos-rust/pull/468
[#469]: https://github.com/cosmos/cosmos-rust/pull/469
[#470]: https://github.com/cosmos/cosmos-rust/pull/470
[#472]: https://github.com/cosmos/cosmos-rust/pull/472
[#473]: https://github.com/cosmos/cosmos-rust/pull/473
> cosmrs v0.17.0

- Cargo.lock
- cosmos-sdk-proto/Cargo.toml
- cosmrs/Cargo.toml
- cosmrs/src/feegrant/basic_allowance.rs
- proto-build/Cargo.toml
This additionally bumps `prost` to v0.13 and `tonic` to v0.12
> Bump tendermint-rs dependencies to v0.38

- cosmos-sdk-proto/Cargo.toml
- cosmos-sdk-proto/src/lib.rs
- cosmos-sdk-proto/src/traits.rs
- cosmrs/Cargo.toml
This PR adds `no_std` support to `cosmos-sdk-proto` in a similar way that `tendermint-proto` chose. (`tendermint-proto` supports `no_std` by default unless the feature `grpc` is enabled. However, checking the feature `std` is a more common way to disable `std`.)
This would be a partial implementation of #397.
> cosmos-sdk-proto: add support for no_std

- cosmrs/src/base/coin.rs
- cosmrs/src/base/denom.rs
These can be used when the gas fee is zero, for example
Fixes #477
> cosmrs: support coins with amount `0`, empty denom

- Cargo.lock
- cosmos-sdk-proto/CHANGELOG.md
- cosmos-sdk-proto/Cargo.toml
- cosmrs/Cargo.toml
- Support for `no_std` ([#478])
- Bump `tendermint-proto` dependency to v0.38 ([#476])
[#476]: https://github.com/cosmos/cosmos-rust/pull/476
[#478]: https://github.com/cosmos/cosmos-rust/pull/478
> cosmos-sdk-proto v0.23.0

- Cargo.lock
- cosmrs/CHANGELOG.md
- cosmrs/Cargo.toml
- Support `Coin` with amount `0` and empty denom ([#479])
- Impl `Default` for `Coin` and `Denom` ([#479])
- Bump tendermint-rs dependencies to v0.38 ([#476])
- Bump `cosmos-sdk-proto` to 0.23 ([#480])
[#476]: https://github.com/cosmos/cosmos-rust/pull/476
[#479]: https://github.com/cosmos/cosmos-rust/pull/479
[#480]: https://github.com/cosmos/cosmos-rust/pull/480
> cosmrs v0.18.0

- Cargo.lock
- Cargo.toml
- cosmos-sdk-proto/Cargo.toml
- cosmrs/Cargo.toml
Also removes `[patch.crates-io]` from Cargo.toml
These releases include some various bugfixes and API changes we need.
> Bump tendermint-rs crates to v0.39.1

- proto-build/buf.sdk.gen.yaml
- proto-build/buf.wasmd.gen.yaml
These were inadvertently added to the config in the wrong place
> proto-build: remove unused tonic opts

- Cargo.lock
- cosmrs/CHANGELOG.md
- cosmrs/Cargo.toml
- Bump tendermint-rs dependencies to v0.39 ([#482], [#483])
- Bump `cosmos-sdk-proto` to v0.24 ([#493])
[#482]: https://github.com/cosmos/cosmos-rust/pull/482
[#483]: https://github.com/cosmos/cosmos-rust/pull/483
[#493]: https://github.com/cosmos/cosmos-rust/pull/493
> cosmrs v0.19.0

- Cargo.lock
- cosmos-sdk-proto/CHANGELOG.md
- cosmos-sdk-proto/Cargo.toml
- cosmrs/Cargo.toml
- Re-export ICS23 proto definitions from the `ics23` crate ([#495])
- Use tendermint proto from `tendermint_proto` instead of `tendermint_proto::v0_34` ([#495])
- IBC protos; use `ibc-proto` crate instead ([#495])
[#495]: https://github.com/cosmos/cosmos-rust/pull/495
cc @romac
> cosmos-sdk-proto v0.25.0-pre.0

- Cargo.lock
- cosmos-sdk-proto/Cargo.toml
- cosmos-sdk-proto/src/lib.rs
As discussed in cosmos/ibc-proto-rs#187, removes this dependency so `ics-proto` can import it directly and we don't need to worry about keeping the two synchronized.
> cosmos-sdk-proto: remove `ics23` dependency

- Cargo.lock
- cosmos-sdk-proto/CHANGELOG.md
- cosmos-sdk-proto/Cargo.toml
- cosmrs/Cargo.toml
- Use tendermint proto from `tendermint_proto` instead of `tendermint_proto::v0_34` ([#495])
- `no_std` + `serde` support ([#500])
- IBC protos; use `ibc-proto` crate instead ([#495])
[#495]: https://github.com/cosmos/cosmos-rust/pull/495
[#500]: https://github.com/cosmos/cosmos-rust/pull/500
> cosmos-sdk-proto v0.25.0

- Cargo.lock
- cosmrs/CHANGELOG.md
- cosmrs/Cargo.toml
- Bump `cosmos-sdk-proto` to v0.25 ([#503])
[#503]: https://github.com/cosmos/cosmos-rust/pull/503
> cosmrs v0.25.0

- Cargo.lock
- cosmos-sdk-proto/Cargo.toml
- cosmrs/Cargo.toml
Synchronize `tendermint-rs` version with ibc-proto-rs `v0.50.0` https://github.com/cosmos/ibc-proto-rs/blob/v0.50.0/CHANGELOG.md#v0500
> Bump `tendermint-rs` to `v0.40.0`

- Cargo.lock
- cosmos-sdk-proto/CHANGELOG.md
- cosmos-sdk-proto/Cargo.toml
- cosmrs/Cargo.toml
- Bump `tendermint-proto` to v0.40 ([#506])
[#506]: https://github.com/cosmos/cosmos-rust/pull/506
> cosmos-sdk-proto v0.26.0

- cosmos-sdk-proto/Cargo.toml
> fix(cosmos-sdk-proto): `no_std` compatible `serde` feature

- cosmrs/src/tx/builder.rs
Fixes adding a non-critical extension to the internal non-critical extension vector instead of to the extension vector.
> fix(cosmrs): `BodyBuilder` non-critical extension add

- Cargo.lock
- cosmrs/CHANGELOG.md
- cosmrs/Cargo.toml
- `BodyBuilder` non-critical extension add ([#516])
[#516]: https://github.com/cosmos/cosmos-rust/pull/516
> cosmrs v0.21.1

- Cargo.lock
- cosmos-sdk-proto/CHANGELOG.md
- cosmos-sdk-proto/Cargo.toml
- cosmos-sdk-proto/README.md
- cosmrs/Cargo.toml
- Bump `tonic` to v0.13; MSRV 1.75 ([#520])
[#520]: https://github.com/cosmos/cosmos-rust/pull/520
> cosmos-sdk-proto v0.27.0

- Cargo.lock
- cosmrs/CHANGELOG.md
- cosmrs/Cargo.toml
- cosmrs/README.md
- Use `Vec::with_capacity` for `MsgFundCommunityPool` ([#511])
- Bump `cosmos-sdk-proto` to v0.27 ([#521])
[#511]: https://github.com/cosmos/cosmos-rust/pull/511
[#521]: https://github.com/cosmos/cosmos-rust/pull/521
> cosmrs v0.22.0
